api/urls.py
from django.urls import path
from .views import ProductsApiView, ProductApiView

app_name = 'api'

urlpatterns = [
    path('products/', ProductsApiView.as_view(), name='productsapi'),
    # One Product API View
    path('product/<int:pk>/', ProductApiView.as_view(), name='productapi')
]

configs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('api.urls'))
]

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'


urlpatterns = [
    # Base Page
    path('', BasePage.as_view(), name='basepage'),
    path('products/', ProductView.as_view(), name='productview'),
    # Add New Product
    path('add_product/', AddProduct.as_view(), name='addproduct'),
    # Delete Product
    path('delete/<int:pk>/', DeleteProduct.as_view(), name='deleteproduct'),
    #Confirm Delete Product
    path('confirm/delete/<int:pk>/', ConfirmDeleteProduct.as_view(), name='confirmdeleteproduct'),
    # Edit Product
    path('edit/product/<int:pk>/', EditProduct.as_view(), name='editproduct'),

    # Category
    path('categories/', CategoryView.as_view(), name='categoriesview'),
    # Add Category class
    path('add_category/', AddCategory.as_view(), name='add_category')
]

templates/product/add_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-3 my-5">
            <h1 class="text-center text-primary">Add New Poduct</h1>
            <form action="{% url 'main:addproduct'%}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Succes</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/product/delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container" style="padding-top: 50px; text-align:center;">
    <div class="col-md-12">
        <h2 style="color:black;">Confirmation</h2>
    <br>
    <h3 style="margin-bottom: 30px;">Do you want to delete {{ product.name }} on {{ pk }} id?</h3>
    <button style="margin-right: 30px;" type="button" class="btn btn-primary"><a href="{% url 'main:confirmdeleteproduct' pk %}" style="text-decoration: none; color:black ;">Continue</a></button> <button type="button" class="btn btn-light" style="background-color: rgba(126, 126, 126, 0.574);"><a href="{% url 'main:productview' %}">Close</a></button>
    </div>
</div>
{% endblock content %}

templates/product/detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} Products {% endblock title %}


{% block extra_styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@6.6.6/css/flag-icons.min.css" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> 
<link rel="stylesheet" href="{% static '' %}">
{% endblock extra_styles %}
{% block content %}
<div class="container mt-5" style="width: 1200px;">
    <div class="top" style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
      <h3 style="color: blue; font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">Products</h3>
      <div class="input-group" style="width: 50%;">
            <input style="border: 1px solid blue;" type="search" class="form-control rounded" placeholder="{% trans 'Search' %}" aria-label="Search" aria-describedby="search-addon" name="search" />
            <button type="button" class="btn btn-outline-primary"><ion-icon name="search-outline"></ion-icon></button>
      </div>
      <button type="button" class="btn btn-primary"><a href="{% url 'main:addproduct' %}" style="color: white; text-decoration: none;">Add new product</a></button>
    </div>

    <div class="col-md-6 mt-6" style="width:100%;display: flex;">
        <table class="table" >
            <thead class="table-light">
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Product id</th>
                <th>Category</th>
                  <th>Description</th>
                <th style="text-align: center;">Status</th>
                <th>Price</th>
                <th style="width: 45px;">Edit</th>
                <th style="width: 45px;">Delete</th>
                <th style="width: 110px;">Add To Card</th>
              </tr>
            </thead>
            {% for item in products %}
            <div>
              <tbody>
                <tr>
                  <td>{{ item.id }}</td>
                  <td><a style="text-decoration: none; color: black;" href="{% url 'main:editproduct' item.id %}">{{ item.name }}</a></td>
                  <td><a style="text-decoration: none ;color: black;" href="#">{{ item.product_id }}</a></td>
                  <td><a style="text-decoration: none; color: black;" href="#">{{ item.category }}</a></td>
                  <td><a style="text-decoration: none; color: black;" href="#">{{ item.description }}</a></td>
                  {% if item.status == '1' %}
                        <td><p style="border: 1px solid blue; text-align: center;background-color: blue;color: white; border-radius: 20px;">Active</p></td>
                  {% else %}
                        <td><p style="text-align: center; border: 1px solid rgb(132, 125, 125, 0.674);background-color:rgba(132, 125, 125, 0.674) ;border-radius: 20px;">Inactive</p></td>
                  {% endif %}
                  <td>{{ item.price }}$</td>
                  <td><button type="submit" style="color: blue; text-decoration: none;"><a href="{% url 'main:editproduct' item.id %}">Edit</a></button></td>
                  <td><button type="submit" style=" text-decoration: none;"><a href="{% url 'main:deleteproduct' item.id %}">Delete</a></button></td>
                  <td><button type="submit" style=" text-decoration: none;"><a href="#">Add</a></button></td>
                  
                </tr>
              </tbody>
            </div>
            
          {% endfor %}
        </table>
        
    </div>
    {% include 'paginations.html' with page=products %}
    
</div>

<p class='apiproduct' style="position: fixed;bottom: 30px;right: 40px;border: 2px solid black; padding: 5px; border-radius: 5px;"><a href="{% url 'api:productsapi' %}" style="text-decoration: none;">API of Product</a></p>

{% endblock content %}

templates/product/edit_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-3 my-5">
            <h1 class="text-center text-primary">'Edit Product</h1>
            <form action="{% url 'main:editproduct' pk %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Edit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}