api/urls.py
from django.urls import path
from .views import ProductsApiView, ProductApiView

app_name = 'api'

urlpatterns = [
    path('products/', ProductsApiView.as_view(), name='productsapi'),
    # One Product API View
    path('product/<int:pk>/', ProductApiView.as_view(), name='productapi')
]

configs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('api.urls'))
]

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'


urlpatterns = [
    # Base Page
    path('', BasePage.as_view(), name='basepage'),
    path('products/', ProductView.as_view(), name='productview'),
    # Add New Product
    path('add_product/', AddProduct.as_view(), name='addproduct'),
    # Delete Product
    path('delete/<int:pk>/', DeleteProduct.as_view(), name='deleteproduct'),
    #Confirm Delete Product
    path('confirm/delete/<int:pk>/', ConfirmDeleteProduct.as_view(), name='confirmdeleteproduct'),
    # Edit Product
    path('edit/product/<int:pk>/', EditProduct.as_view(), name='editproduct'),

    # Category
    path('categories/', CategoryView.as_view(), name='categoriesview'),
    # Add Category class
    path('add_category/', AddCategory.as_view(), name='add_category')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% block extra_styles %}
    {% endblock extra_styles %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main:basepage' %}">Pizdes shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link " href="{% url 'main:productview' %}" tabindex="-1" aria-disabled="true">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'main:categoriesview' %}" tabindex="-1" aria-disabled="true">Categories</a>
        </li>
      </ul>
      <a href="#" style="text-decoration:none;">Sign Up</a>
      <a style="margin:0px 10px; text-decoration:none;" href="#">Sign In</a>
    </div>
  </div>
</nav>



{% block content %}

{% endblock content %}
</body>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

</html>

templates/paginations.html
<div class="page" style="display: flex;
justify-content: center;">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page.has_other_pages %}
         {% if page.has_previous %} 
         <li class="page-item">
            <a class="page-link" style="color: rgb(10, 10, 10);" href="?page={{ page.previous_page_number }}" aria-label="Previous">
               <span aria-hidden="true">&laquo;</span>
            </a>
         </li>
      {% endif %}
      {% for i in page.paginator.page_range %}
         {% if page.number == i %}
            <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
         {% elif i >= page.number|add:-2 and i <= page.number|add:2 %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
         {% endif %}
      {% endfor %}
      {% if page.has_next %}
      <li class="page-item">
         <a style=" color: rgb(0, 0, 0);" class="page-link" href="?page={{ page.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
         </a>
      </li>
      {% endif %}
     </ul>
    </nav>
    {% endif %}
</div>